#!/bin/bash

SUBJECT_TOKEN="eyJraWQiOiJ0ZXN0LWtleS1pZCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJuL2EiLCJpc3MiOiJuZGYtdG9rZW4tZXhjaGFuZ2UtZGV2IiwibmJmIjoxNDkwMjY1NTgxLCJleHAiOjE0OTExMjk1ODEsImlhdCI6MTQ5MDI2NTU4MSwianRpIjoiOTdlN2Q1ZGQtMTg3YS00ODA2LTliMjktYmVkZTk5MDM1YTMwIiwiYXVkIjoibmRmLXRva2VuLWV4Y2hhbmdlIiwidWlkIjoiMDExMDgzMjA0MTUiLCJjaWQiOiIwMTEwODMyMDQxNSIsImNsaWVudF9pZCI6IlBOTk8iLCJjIjoiTk8iLCJhbSI6ImJhbmtpZF9ubyIsImNoIjoiUE5OTyIsInNnbSI6ImhvdXNlaG9sZCIsInNpZCI6ImQyMTIzZDcxLTlmM2UtNDY5Yy05ZTU1LWI4ZTRlYTdkMmJhMCIsInNzbiI6IjAxMTA4MzIwNDE1IiwiYWlkIjoxMjM0NTZ9.Xx5jBtvtofUj8gFJXO8f5thksBPCntWr5x3zFfWOVAyodcINGP553pCk3n8MaG36OJ31ezlPqIhnu3P4OQx3mUVtcy-8a5fbkW3OQiCigkX_GHYbsQVSbJeF4jj4NU49nriv46CUzPEhbU2vufEjZFtzVYBJ6w9LWEU1zB3ACts" \
&& \
echo $SUBJECT_TOKEN \
&& \
curl -v -H "Content-Type: application/x-www-form-urlencoded" \
-d "grant_type=urn:ietf:params:oauth:grant-type:token_exchange&subject_token=${SUBJECT_TOKEN}&subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
http://localhost:8084/oauth/token
